### PR TITLE
Support `cargo-udeps`

### PR DESCRIPTION
**Pull request by gifnksm**
[`cargo-udeps`](https://github.com/est31/cargo-udeps) is a tool to find unused dependencies.
It is useful to keep the binary size of the crate no larger than necessary.

To run `cargo-udeps` on a crate with many combinations of features, it is better to use GitHub Actions.
I want to use this action to easily use `cargo-udeps`, so I created this pull request.

This action falls back to `cargo-binstall` by default when trying to install an unknown package, but it did not work well in my environment.

* On macOS, an installation by `cargo-binstall` failed.
  * [macOS CI log](https://github.com/gifnksm/souko/runs/7815942187) (Job is successful because the error was ignored)
* On Linux/Windows,` cargo-udeps` could not find when cargo directory is restored by a cache
  * [Linux CI log](https://github.com/gifnksm/souko/runs/7815942148)
  * [Windows CI log](https://github.com/gifnksm/souko/runs/7815942224)

I don't know why this occurred, but with this pull request, the installation succeeded and I was able to use `cargo-udeps` as expected.

* [Linux CI log with this PR](https://github.com/gifnksm/souko/runs/7816399464)
* [macOS CI log with this PR](https://github.com/gifnksm/souko/runs/7816399492)
* [Windows CI log with this PR](https://github.com/gifnksm/souko/runs/7816399507)

### CODE REVIEW

**Comment by NobodyXu** [comment]
@gifnksm That's strange since we already use create_dir_all to ensure dirs exist before installing.

**Comment by NobodyXu** [comment]
@gifnksm For ubuntu and win, what happened isna caching problem.

cargo-binstall writes metadata about crates installed to $CARGO_HOME/binstall/crates-v1.json and skip when asked to install again.

**Review by taiki-e — APPROVED** [review]
Thanks!

**Comment by taiki-e** [comment]
Published in 1.11.0.

**Pull request merged**
