### PR TITLE
Add support for zola

### LINKED ISSUE #70: Add support for zola
I'd like to request support for https://github.com/getzola/zola. It's a static website generator with a solid usecase in github actions.

### PR DESCRIPTION
**Pull request by tranzystorek-io**
Closes #70

### CODE REVIEW

**Comment by taiki-e** [comment]
Thanks! Could you add zola to this line as well? 
https://github.com/taiki-e/install-action/blob/6e270f6359e00e6e4b83c8edc6d769c1947b7f5b/.github/workflows/ci.yml#L102-L104

**Comment by tranzystorek-io** [comment]
It fails the test on some of those containers if I add it there: https://github.com/taiki-e/install-action/actions/runs/4148390689

**Comment by taiki-e** [comment]
Oh, in that case, it is ok as is. (I will need to split the matrix into a glibc 2.31+ group and a 2.27+ group later.)

**Review by taiki-e — APPROVED** [review]

**Comment by taiki-e** [comment]
Published in 2.4.0.

**Pull request merged**
