### PR TITLE
Update manifest

### PR DESCRIPTION
**Pull request by taiki-e**
Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).

This will be auto-merged when CI has passed because this is an auto-generated PR in a defined format and is usually considered no additional review is required.

### CODE REVIEW

**Comment by taiki-e** [comment]
https://github.com/taiki-e/install-action/actions/runs/10361493230/job/28681918253

```
info: installing wasm-bindgen@latest
info: downloading https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.93/wasm-bindgen-0.2.93-x86_64-apple-darwin.tar.gz
info: verifying sha256 checksum for wasm-bindgen-0.2.93-x86_64-apple-darwin.tar.gz
info: wasm-bindgen-test-runner installed at /Users/runner/.cargo/bin/wasm-bindgen-test-runner
info: wasm-bindgen installed at /Users/runner/.cargo/bin/wasm-bindgen
info: wasm2es6js installed at /Users/runner/.cargo/bin/wasm2es6js
+ wasm-bindgen --version
/Users/runner/work/install-action/install-action/.//main.sh: line 11: /Users/runner/.cargo/bin/wasm-bindgen: Bad CPU type in executable
+ wasm-bindgen --help
/Users/runner/work/install-action/install-action/.//main.sh: line 11: /Users/runner/.cargo/bin/wasm-bindgen: Bad CPU type in executable
```

I guess wasm-bindgen-0.2.93-x86_64-apple-darwin.tar.gz contains aarch64 binaries. (The current macos-latest runner is macos-14 (aarch64) and the previous macos-latest runner was macos-12 (x86_64), and [dist_macos_x86_64 doesn't specify the target](https://github.com/rustwasm/wasm-bindgen/blob/ee049dc870954ca75191eb1c69ccd1247fb18650/.github/workflows/main.yml#L441).)
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

cc @daxpedda

**Comment by daxpedda** [comment]
Thank you for the ping!
I fixed the CI producing the wrong binaries and updated the release binaries!

**Comment by taiki-e** [comment]
@daxpedda Thanks for the quick response. It seems that the newly uploaded archives have a directory structure that is not consistent with the others...

```console
# https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.93/wasm-bindgen-0.2.93-x86_64-apple-darwin.tar.gz
$ tar xvf wasm-bindgen-0.2.93-x86_64-apple-darwin.tar.gz     
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/wasm-bindgen
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/wasm-bindgen-test-runner
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/README.md
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/wasm2es6js
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/LICENSE-MIT
wasm-bindgen-0.2.93-2-g0f0b4e2d-x86_64-apple-darwin/LICENSE-APACHE

# https://github.com/rustwasm/wasm-bindgen/releases/download/0.2.93/wasm-bindgen-0.2.93-aarch64-apple-darwin.tar.gz
$ tar xvf wasm-bindgen-0.2.93-aarch64-apple-darwin.tar.gz    
wasm-bindgen-0.2.93-aarch64-apple-darwin/
wasm-bindgen-0.2.93-aarch64-apple-darwin/wasm-bindgen
wasm-bindgen-0.2.93-aarch64-apple-darwin/wasm-bindgen-test-runner
wasm-bindgen-0.2.93-aarch64-apple-darwin/README.md
wasm-bindgen-0.2.93-aarch64-apple-darwin/wasm2es6js
wasm-bindgen-0.2.93-aarch64-apple-darwin/LICENSE-MIT
wasm-bindgen-0.2.93-aarch64-apple-darwin/LICENSE-APACHE
```

**Comment by daxpedda** [comment]
Right, addressed now as well.

**Pull request merged**
