### PR TITLE
Add support for cargo-dinghy

### LINKED ISSUE #132: Add support for installing cargo-dinghy

### PR DESCRIPTION
**Pull request by notgull**
Closes #132

### CODE REVIEW

**Comment by notgull** [comment]
> cargo-dinghy's archive seems to be an archive of [a directory containing binary](https://github.com/sonos/dinghy/blob/f22f0bd9f34f5e7d2cc75a6943779e7b6643a00f/.github/workflows/binaries.yml#L31), so perhaps `bin` field ([example](https://github.com/taiki-e/install-action/blob/b02c385974187109775c7cabe0c72778b6e9b571/tools/codegen/base/cargo-deny.json#L5)) is needed.

Fixed!

**Review by NobodyXu — APPROVED** [review]

**Comment by taiki-e** [comment]
LGTM. Could you add cargo-dinghy to the following tool lists?

https://github.com/taiki-e/install-action/blob/7bda3b1d5e4f0b183b453259c3b03dcfa68c6be2/.github/workflows/ci.yml#L44-L47

https://github.com/taiki-e/install-action/blob/7bda3b1d5e4f0b183b453259c3b03dcfa68c6be2/.github/workflows/ci.yml#L105-L107

**Review by taiki-e — APPROVED** [review]
Thanks!

**Comment by taiki-e** [comment]
Published in 2.11.0.

**Pull request merged**
