### PR TITLE
Add support for cargo-machete

### PR DESCRIPTION
**Pull request by tgnottingham**

### CODE REVIEW

**Comment by tgnottingham** [comment]
The [CI failure](https://github.com/taiki-e/install-action/actions/runs/5907873053/job/16026509633?pr=196) appears to be unrelated to this change.

**Review by NobodyXu — APPROVED** [review]
LGTM

**Review by taiki-e — APPROVED** [review]
Thanks!

**Comment by taiki-e** [comment]
Published in 2.16.0.

**Pull request merged**
